In [11]:
import numpy as np

In [12]:
a = np.arange(10, 71, 10)
b = np.arange(1, 8)
a, b

(array([10, 20, 30, 40, 50, 60, 70]), array([1, 2, 3, 4, 5, 6, 7]))

In [13]:
a+b

array([11, 22, 33, 44, 55, 66, 77])

In [14]:
a-b

array([ 9, 18, 27, 36, 45, 54, 63])

In [15]:
a*b

array([ 10,  40,  90, 160, 250, 360, 490])

In [16]:
a+5

array([15, 25, 35, 45, 55, 65, 75])

In [17]:
b**2

array([ 1,  4,  9, 16, 25, 36, 49])

In [19]:
a *= 2 #a = a * 2
a

array([ 20,  40,  60,  80, 100, 120, 140])

In [21]:
a = a /3 # a /= 3
a

array([ 6.66666667, 13.33333333, 20.        , 26.66666667, 33.33333333,
       40.        , 46.66666667])

In [25]:
arr1 = np.array([1,2,3]).reshape(1,3)
arr1

array([[1, 2, 3]])

In [27]:
arr2 = np.array([1,2,3]).reshape(3,1)
arr2

array([[1],
       [2],
       [3]])

In [28]:
arr1 * arr2

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [31]:
#1 + 4 + 9
result = np.dot(arr1, arr2)
result.shape

(1, 1)

In [32]:
arr3 = arr1 * arr2
arr3

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [33]:
np.dot(arr3, arr2)

array([[14],
       [28],
       [42]])

#### Choosing data from array

In [34]:
np.random.seed(0)
arr = np.random.randint(-10, 11, (7,8))
arr

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [  8,  -6,  -4,   2,  -9,  -4,  -3,   4],
       [  7,  -5,   3,  -2,  -1,  10,   9,   6],
       [  9,  -5,   5,   5, -10,   8,  -7,   7],
       [  9,   9,   9,   4,  -3, -10,  -9,  -1],
       [-10,   0,  10,  -7,   1,   8,  -8, -10],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [36]:
# getting last row
arr[6], arr[-1]

(array([-10,  -6,  -5,  -4,  -2,  10,   7,   5]),
 array([-10,  -6,  -5,  -4,  -2,  10,   7,   5]))

In [37]:
# getting first and last
arr[ [0,6] ]

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [41]:
# getting 2nd and 3rd row and every 3rd columns
arr[ 1:3 , ::3 ]

array([[ 8,  2, -3],
       [ 7, -2,  9]])

In [42]:
# getting last column
arr[ : , -1 ]

array([  9,   4,   6,   7,  -1, -10,   5])

In [45]:
arr.transpose()[-1]

array([  9,   4,   6,   7,  -1, -10,   5])

In [47]:
arr.T[-1]

array([  9,   4,   6,   7,  -1, -10,   5])

In [52]:
for i in range(len(arr)):
    print(arr[i])
    print("="*50)

[  2   5 -10  -7  -7  -3  -1   9]
[ 8 -6 -4  2 -9 -4 -3  4]
[ 7 -5  3 -2 -1 10  9  6]
[  9  -5   5   5 -10   8  -7   7]
[  9   9   9   4  -3 -10  -9  -1]
[-10   0  10  -7   1   8  -8 -10]
[-10  -6  -5  -4  -2  10   7   5]


In [56]:
print("ABCABCABCABC")
print("ABC"*10)
print("=================================================")
print("="*80)

ABCABCABCABC
ABCABCABCABCABCABCABCABCABCABC


In [53]:
for row in arr:
    print(row)
    print("="*50)

[  2   5 -10  -7  -7  -3  -1   9]
[ 8 -6 -4  2 -9 -4 -3  4]
[ 7 -5  3 -2 -1 10  9  6]
[  9  -5   5   5 -10   8  -7   7]
[  9   9   9   4  -3 -10  -9  -1]
[-10   0  10  -7   1   8  -8 -10]
[-10  -6  -5  -4  -2  10   7   5]


#### Compare speed Python list vs Numpy arrays

In [63]:
%%timeit -r 10 -n 2000
[x**2 for x in range(1,1_001) ]

224 µs ± 6.92 µs per loop (mean ± std. dev. of 10 runs, 2,000 loops each)


In [64]:
%%timeit -r 10 -n 2000
np.arange(1, 1_001)**2

The slowest run took 4.20 times longer than the fastest. This could mean that an intermediate result is being cached.
2.83 µs ± 1.79 µs per loop (mean ± std. dev. of 10 runs, 2,000 loops each)


In [65]:
224/3

74.66666666666667