In [1]:
import numpy as np

In [2]:
# classic way in Python list for filtering
numbers_list = [ -20, -1, 10, 50, -100, 100, -512, 123, 432, 111, -1024]
# only positive numbers
[x for x in numbers_list if x>0 ]

[10, 50, 100, 123, 432, 111]

In [3]:
arr = np.array(numbers_list)
arr

array([  -20,    -1,    10,    50,  -100,   100,  -512,   123,   432,
         111, -1024])

In [5]:
arr[ arr>0 ]

array([ 10,  50, 100, 123, 432, 111])

In [7]:
# find values >=0 and <=100
# FALSE and FALSE -> FALSE
# FALSE and TRUE -> FALSE
# TRUE and FALSE -> FALSE
# TRUE and TRUE -> TRUE
a = -100
if a>=0 and a<=100:
    print("OK")
else:
    print("ERROR")

ERROR


In [9]:
# & - bitwise and , similar to AND logical operator
arr[ (arr>=0)&(arr<=100) ]

array([ 10,  50, 100])

In [12]:
# find values <0 or >100
# FALSE or FALSE -> FALSE
# FALSE or TRUE -> TRUE
# TRUE or FALSE -> TRUE
# TRUE or TRUE -> TRUE
a = 50
if a>=0 or a<=100:
    print("OK")
else:
    print("ERROR")

OK


In [14]:
# | - bitwise or , similar to OR logical operator
arr[ (arr<0)|(arr>100) ]

array([  -20,    -1,  -100,  -512,   123,   432,   111, -1024])

In [26]:
# NOT operator example
# FALSE -> not TRUE
# TRUE -> not FALSE
a = 0
if not a>10:
    print("not > 10")
else:
    print("not <= 10")

not > 10


In [27]:
not (4 % 2 == 0)

False

In [19]:
(4 % 2 == 0)

True

In [23]:
print(a>100)
#print(a<=100)
print(not a>100)

False
True


In [28]:
# create array with NaN (not a number) or missing values
arr = np.array([-1, 4, 10, np.NaN, 15, 20, np.NaN])
arr

array([-1.,  4., 10., nan, 15., 20., nan])

In [29]:
arr.dtype

dtype('float64')

In [34]:
# ~ - bitwise not operator (tilde) aka  swung dash 
~np.isnan(arr)

array([ True,  True,  True, False,  True,  True, False])

In [35]:
arr[ ~np.isnan(arr) ]

array([-1.,  4., 10., 15., 20.])

In [36]:
not np.isnan(arr)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()